### ISSUE TITLE
Can,t recieved server list

### ISSUE THREAD

**Issue by iman100** [MrShailandra/TurtleVPN#2]
hi

```

private final String BASE_URL = "http://www.vpngate.net/api/iphone/";
private final String BASE_FILE_NAME = "vpngate.csv";
```
I can not connect to Iran's main vpngate server to get the list of servers
There is a way to get the file above somewhere else

**Comment by MrShailandra** [comment]
Hi, 
I don't think there is another API URL. 
After Searching on Google I find that Iran government had blocked VPN services that's why VPNGATE not working There.
